theme: jekyll-theme-cayman
baseurl: ""

# Custom settings for Cayman theme
title: "n8n Arena: Creators Leaderboard"
description: "Community-powered rankings of top creators and standout workflows"

# Custom buttons
github:
  is_project_page: true
custom_buttons:
  - text: Templates gallery
    url: https://n8n.partnerlinks.io/n8n-workflows
  - text: What is this?
    url: /about
  - text: What is n8n?
    url: /n8n

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/n8narena.png
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"

collections:
  creators:
    output: true
    permalink: /creators/:name/index.html
    # files_dir: 'creators'
  guides:
    output: true
    permalink: /guides/:path/

# Configure webrick for local development
webrick:
  headers:
    DirectoryIndex: index.html

# Include underscore folders
include:
  - _creators
  - _guides

# Define your static pages for the sitemap
sitemap_pages:
  - /
  - /about/
  - /n8n/
  - /workflows/
  - /guides/
