theme: jekyll-theme-cayman
baseurl: "/caymantest.github.io"

# Custom settings for Cayman theme
title: n8n Creators Leaderboard
description: A community-led website with creator ratings and workflow template analytics

# Custom buttons
github:
  is_project_page: true
custom_buttons:
  - text: Workflow ratings
    url: /caymantest.github.io/workflows
  - text: Templates gallery
    url: https://n8n.partnerlinks.io/n8n-workflows
  - text: What is this?
    url: /caymantest.github.io/about
  - text: What is n8n?
    url: /caymantest.github.io/n8n
