theme: jekyll-theme-cayman
baseurl: "/n8n-community-leaderboard"

# Custom settings for Cayman theme
title: n8n Creators Leaderboard
description: A community-led website with creator ratings and workflow template analytics

# Custom buttons
github:
  is_project_page: true
custom_buttons:
  - text: Workflow ratings
    url: /n8n-community-leaderboard/workflows
  - text: Templates gallery
    url: https://n8n.partnerlinks.io/n8n-workflows
  - text: What is this?
    url: /n8n-community-leaderboard/about
  - text: What is n8n?
    url: /n8n-community-leaderboard/n8n
